//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NServiceBus.EventSourceLogging.Samples.CustomEventLog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NServiceBus.EventSourceLogging.Samples.CustomEventLog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MESSAGE .Net 4.5 {0} : {1}.
        /// </summary>
        internal static string event_Debug {
            get {
                return ResourceManager.GetString("event_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MESSAGE .Net 4.5 {0} : {1} : {2} : {3} : {4}.
        /// </summary>
        internal static string event_DebugException {
            get {
                return ResourceManager.GetString("event_DebugException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MESSAGE .Net 4.5 {0} : {1}.
        /// </summary>
        internal static string event_Error {
            get {
                return ResourceManager.GetString("event_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MESSAGE .Net 4.5 {0} : {1} : {2} : {3} : {4}.
        /// </summary>
        internal static string event_ErrorException {
            get {
                return ResourceManager.GetString("event_ErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MESSAGE .Net 4.5 {0} : {1}.
        /// </summary>
        internal static string event_Fatal {
            get {
                return ResourceManager.GetString("event_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MESSAGE .Net 4.5 {0} : {1} : {2} : {3} : {4}.
        /// </summary>
        internal static string event_FatalException {
            get {
                return ResourceManager.GetString("event_FatalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MESSAGE .Net 4.5 {0} : {1}.
        /// </summary>
        internal static string event_Info {
            get {
                return ResourceManager.GetString("event_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MESSAGE .Net 4.5 {0} : {1} : {2} : {3} : {4}.
        /// </summary>
        internal static string event_InfoException {
            get {
                return ResourceManager.GetString("event_InfoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MESSAGE .Net 4.5 {0} : {1}.
        /// </summary>
        internal static string event_Warn {
            get {
                return ResourceManager.GetString("event_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MESSAGE .Net 4.5 {0} : {1} : {2} : {3} : {4}.
        /// </summary>
        internal static string event_WarnException {
            get {
                return ResourceManager.GetString("event_WarnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to log a message with an invalid format: .
        /// </summary>
        internal static string InvalidFormatErrorString {
            get {
                return ResourceManager.GetString("InvalidFormatErrorString", resourceCulture);
            }
        }
    }
}
